# Generated by Django 2.1.2 on 2021-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
