# Generated by Django 2.1.2 on 2021-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacons', '0002_auto_20210131_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=17),
        ),
    ]
