# Generated by Django 2.1.2 on 2021-02-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacons', '0003_auto_20210207_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
    ]
