# Generated by Django 2.1.2 on 2020-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('LF', 'Lost and Found'), ('SL', 'Stolen item')], default='LF', max_length=2),
        ),
    ]
